apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce   
          # Can be used for read and write by single node at a time 
